import { useState, useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Loader } from '../../common';
import { userApi } from '../../../api/userApi';
import {
  createUserSuccess,
  updateUserSuccess,
  closeFormModal,
  setError,
  selectSelectedUser,
  selectUserFormMode,
  selectUserError,
  selectCurrentOrg,
} from '../../../store/slices/userSlice';
import styles from './UserForm.module.css';

/**
 * User Form Component
 * Handles both creation and editing of users
 */
const UserForm = () => {
  const dispatch = useDispatch();
  const selectedUser = useSelector(selectSelectedUser);
  const formMode = useSelector(selectUserFormMode);
  const error = useSelector(selectUserError);
  const currentOrg = useSelector(selectCurrentOrg);

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [validationErrors, setValidationErrors] = useState({});

  // Form data state (password is auto-generated on create, cannot be changed on edit)
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    userType: 'org_user',
  });

  // Populate form when editing
  useEffect(() => {
    if (formMode === 'edit' && selectedUser) {
      setFormData({
        name: selectedUser.name || '',
        email: selectedUser.email || '',
        userType: selectedUser.userType || 'org_user',
        status: selectedUser.status || 'active',
      });
    } else {
      setFormData({
        name: '',
        email: '',
        userType: 'org_user',
      });
    }
  }, [formMode, selectedUser]);

  // Validation function
  const validateForm = () => {
    const errors = {};

    // Name validation
    if (!formData.name.trim()) {
      errors.name = 'Name is required';
    } else if (formData.name.length < 2) {
      errors.name = 'Name must be at least 2 characters';
    } else if (formData.name.length > 100) {
      errors.name = 'Name must be less than 100 characters';
    }

    // Email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!formData.email.trim()) {
      errors.email = 'Email is required';
    } else if (!emailRegex.test(formData.email)) {
      errors.email = 'Please enter a valid email address';
    }

    // Password is auto-generated on create, cannot be changed on edit

    setValidationErrors(errors);
    return Object.keys(errors).length === 0;
  };

  // Handle input change
  const handleChange = (e) => {
    const { name, value } = e.target;
    
    // Clear validation error when user starts typing
    if (validationErrors[name]) {
      setValidationErrors(prev => ({ ...prev, [name]: undefined }));
    }

    setFormData(prev => ({ ...prev, [name]: value }));
  };

  // Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    setIsSubmitting(true);

    try {
      if (formMode === 'edit') {
        // Prepare update payload (password cannot be changed via edit)
        const payload = {
          name: formData.name,
          email: formData.email,
          userType: formData.userType,
          status: formData.status,
        };

        const response = await userApi.update(selectedUser.id, payload);
        dispatch(updateUserSuccess(response.data));
      } else {
        // Create payload (password is auto-generated by backend)
        const payload = {
          name: formData.name,
          email: formData.email,
          userType: formData.userType,
        };

        const response = await userApi.create(payload, currentOrg.orgId, currentOrg.orgName);
        dispatch(createUserSuccess(response.data));
      }
    } catch (err) {
      dispatch(setError(err.data?.message || err.message || 'An error occurred'));
    } finally {
      setIsSubmitting(false);
    }
  };

  // Handle cancel
  const handleCancel = () => {
    dispatch(closeFormModal());
  };

  return (
    <form className={styles.form} onSubmit={handleSubmit}>
      {error && (
        <div className={styles.error}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <circle cx="12" cy="12" r="10" />
            <line x1="12" y1="8" x2="12" y2="12" />
            <line x1="12" y1="16" x2="12.01" y2="16" />
          </svg>
          <span>{error}</span>
        </div>
      )}

      {/* Organization Info (Read-only) */}
      <div className={styles.orgBadge}>
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M19 21V5a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v16" />
          <path d="M19 21H5" />
        </svg>
        <span>{currentOrg.orgName}</span>
      </div>

      {/* User Information Section */}
      <div className={styles.section}>
        <h3 className={styles.sectionTitle}>
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" />
            <circle cx="12" cy="7" r="4" />
          </svg>
          User Information
        </h3>

        <div className={styles.inputGroup}>
          <label htmlFor="name" className={styles.label}>
            Full Name <span className={styles.required}>*</span>
          </label>
          <input
            type="text"
            id="name"
            name="name"
            value={formData.name}
            onChange={handleChange}
            className={`${styles.input} ${validationErrors.name ? styles.inputError : ''}`}
            placeholder="Enter full name"
          />
          {validationErrors.name && <span className={styles.fieldError}>{validationErrors.name}</span>}
        </div>

        <div className={styles.inputGroup}>
          <label htmlFor="email" className={styles.label}>
            Email <span className={styles.required}>*</span>
          </label>
          <input
            type="email"
            id="email"
            name="email"
            value={formData.email}
            onChange={handleChange}
            className={`${styles.input} ${validationErrors.email ? styles.inputError : ''}`}
            placeholder="user@example.com"
          />
          {validationErrors.email && <span className={styles.fieldError}>{validationErrors.email}</span>}
        </div>

        {/* Password info note */}
        {formMode === 'create' && (
          <div className={styles.infoBox}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <circle cx="12" cy="12" r="10" />
              <line x1="12" y1="16" x2="12" y2="12" />
              <line x1="12" y1="8" x2="12.01" y2="8" />
            </svg>
            <span>Password will be auto-generated: first 4 letters of email + "_" + first 4 letters of name (lowercase). Example: <code>john_john</code> for john.doe@example.com + John Doe</span>
          </div>
        )}

        <div className={styles.row}>
          <div className={styles.inputGroup}>
            <label htmlFor="userType" className={styles.label}>User Type</label>
            <select
              id="userType"
              name="userType"
              value={formData.userType}
              onChange={handleChange}
              className={styles.select}
            >
              <option value="org_user">Organization User</option>
              <option value="org_admin">Organization Admin</option>
            </select>
          </div>

          {formMode === 'edit' && (
            <div className={styles.inputGroup}>
              <label htmlFor="status" className={styles.label}>Status</label>
              <select
                id="status"
                name="status"
                value={formData.status}
                onChange={handleChange}
                className={styles.select}
              >
                <option value="active">Active</option>
                <option value="suspended">Suspended</option>
              </select>
            </div>
          )}
        </div>
      </div>

      {/* Actions */}
      <div className={styles.actions}>
        <button
          type="button"
          className={styles.cancelBtn}
          onClick={handleCancel}
          disabled={isSubmitting}
        >
          Cancel
        </button>
        <button
          type="submit"
          className={styles.submitBtn}
          disabled={isSubmitting}
        >
          {isSubmitting ? (
            <Loader size="small" variant="dots" />
          ) : (
            <>
              <span>{formMode === 'edit' ? 'Update User' : 'Create User'}</span>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <polyline points="20 6 9 17 4 12" />
              </svg>
            </>
          )}
        </button>
      </div>
    </form>
  );
};

export default UserForm;

